# Generated by Django 5.2.7 on 2025-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
