# Generated by Django 5.2.7 on 2025-10-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userss_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userss',
            new_name='User',
        ),
    ]
